services:
  mysql:
    user: 501:20
    image: mysql:8.0.33
    ports:
      - 13306:3306
    volumes:
      - ${HOST_VOLUME}
      - ${CONTAINER_VOLUME}
    command:
      - '--character-set-server=utf8mb4'
      - '--collation-server=utf8mb4_unicode_ci'
    environment:
      MYSQL_ROOT_PASSWORD: ${ROOT_PASSWORD}
      MYSQL_DATABASE: wanted
